name: ici_menu
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  get_it: ^7.6.0
  injectable: ^2.1.2
  retrofit: ^4.0.1
  freezed_annotation: ^2.2.0
  easy_localization: ^3.0.2
  shared_preferences: ^2.1.2
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.3.6
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.1+1
  freezed: ^2.3.5
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
